version: '3.9'
services:
  dns-checker-cache:
    image: redis:latest
    networks:
      - toncenter-network
    deploy:
      mode: replicated
      replicas: 1
  dns-checker:
    image: localhost:5000/ton-dns-checker:latest
    build:
      context: .
      dockerfile: Dockerfile
    # command: -c "uvicorn dnschecker.mock:app --host 0.0.0.0 --port 8081"
    command: -c "uvicorn dnschecker.main:app --host 0.0.0.0 --port 8081"
    networks:
      - main
    secrets:
      - global-config
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthcheck"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 40s
networks:
  main:
    attachable: true
    external: false
secrets:
  global-config:
    file: private/global-config.json
