version: '3.9'
services:
  dnschecker-backend:
    image: localhost:5000/dns-check-backend:latest
    build:
      context: backend
      dockerfile: Dockerfile
    # command: -c "uvicorn dnschecker.mock:app --host 0.0.0.0 --port 8081"
    command: -c "python3 main.py"
    networks:
      - toncenter-network
    deploy:
      mode: replicated
      replicas: 1
networks:
  toncenter-network:
    external: true
secrets:
  global-config:
    file: private/global-config.json